/**
 * cross_sdk.test.ts — Vitest: verify Python-signed JWTs in TypeScript.
 *
 * Loads fixtures.json (generated by generate_fixtures.py) and asserts that
 * the TypeScript SDK can verify every token Python signed, and correctly
 * rejects tampered tokens.
 *
 * Run from packages/agentpassport-ts/:
 *   npx vitest run ../../tests/cross-sdk/cross_sdk.test.ts
 */

import { describe, it, expect, beforeAll } from "vitest";
import { readFileSync } from "fs";
import { join, dirname } from "path";
import { fileURLToPath } from "url";

import { verifyAuthChain } from "../../packages/agentpassport-ts/src/jwt.js";

const __dirname = dirname(fileURLToPath(import.meta.url));

interface Party {
  did: string;
  public_key_hex: string;
}

interface Fixtures {
  generated_by: string;
  single_hop: {
    issuer_did: string;
    issuer_public_key_hex: string;
    subject_did: string;
    token: string;
    scope: string[];
  };
  three_hop_chain: {
    parties: Party[];
    chain: string[];
    expected_subject_did: string;
  };
  tampered_token: {
    issuer_did: string;
    issuer_public_key_hex: string;
    subject_did: string;
    token: string;
  };
}

function hexToBytes(hex: string): Uint8Array {
  const bytes = new Uint8Array(hex.length / 2);
  for (let i = 0; i < hex.length; i += 2) {
    bytes[i / 2] = parseInt(hex.slice(i, i + 2), 16);
  }
  return bytes;
}

let fixtures: Fixtures;

beforeAll(() => {
  const fixturePath = join(__dirname, "fixtures.json");
  fixtures = JSON.parse(readFileSync(fixturePath, "utf-8"));
  expect(fixtures.generated_by).toBe("python");
});

describe("Scenario 1 — Python signs, TypeScript verifies (single-hop)", () => {
  it("verifies a Python-signed single-hop delegation JWT", () => {
    const { single_hop } = fixtures;
    const knownPublicKeys = new Map([
      [single_hop.issuer_did, hexToBytes(single_hop.issuer_public_key_hex)],
    ]);

    const result = verifyAuthChain({
      chain: [single_hop.token],
      expectedSubject: single_hop.subject_did,
      knownPublicKeys,
    });

    expect(result).toBe(true);
  });
});

describe("Scenario 3 — Python builds 3-hop chain, TypeScript verifies", () => {
  it("verifies the full 3-hop chain signed by Python", () => {
    const { three_hop_chain } = fixtures;

    // Build the known-keys map from all parties except the leaf
    // (leaf is the subject, not an issuer)
    const knownPublicKeys = new Map<string, Uint8Array>(
      three_hop_chain.parties.slice(0, 3).map((p) => [
        p.did,
        hexToBytes(p.public_key_hex),
      ])
    );

    const result = verifyAuthChain({
      chain: three_hop_chain.chain,
      expectedSubject: three_hop_chain.expected_subject_did,
      knownPublicKeys,
    });

    expect(result).toBe(true);
  });

  it("rejects the chain when expected subject is wrong", () => {
    const { three_hop_chain } = fixtures;
    const knownPublicKeys = new Map<string, Uint8Array>(
      three_hop_chain.parties.slice(0, 3).map((p) => [
        p.did,
        hexToBytes(p.public_key_hex),
      ])
    );

    const result = verifyAuthChain({
      chain: three_hop_chain.chain,
      expectedSubject: three_hop_chain.parties[0].did, // wrong — should be leaf
      knownPublicKeys,
    });

    expect(result).toBe(false);
  });
});

describe("Scenario 5 — Tampered Python JWT is rejected by TypeScript", () => {
  it("rejects a tampered Python-signed JWT", () => {
    const { tampered_token } = fixtures;
    const knownPublicKeys = new Map([
      [tampered_token.issuer_did, hexToBytes(tampered_token.issuer_public_key_hex)],
    ]);

    const result = verifyAuthChain({
      chain: [tampered_token.token],
      expectedSubject: tampered_token.subject_did,
      knownPublicKeys,
    });

    expect(result).toBe(false);
  });
});
