"""
test_cross_sdk.py — pytest: verify TypeScript-signed JWTs in Python.

Loads ts_fixtures.json (generated by generate_ts_fixtures.ts) and asserts that
the Python SDK can verify every token TypeScript signed, and correctly rejects
tampered tokens.

Run from repo root:
    PATH=/root/.local/bin:$PATH uv run pytest tests/cross-sdk/test_cross_sdk.py -v
"""

from __future__ import annotations

import json
import os
import sys

import pytest

sys.path.insert(0, os.path.join(os.path.dirname(__file__), "../../packages/agentpassport/src"))

from agentpassport.identity.signing import verify_auth_chain

FIXTURES_PATH = os.path.join(os.path.dirname(__file__), "ts_fixtures.json")


@pytest.fixture(scope="module")
def fixtures() -> dict:
    with open(FIXTURES_PATH) as f:
        data = json.load(f)
    assert data["generated_by"] == "typescript", "Expected fixtures generated by TypeScript"
    return data


# ---------------------------------------------------------------------------
# Scenario 2 — TypeScript signs, Python verifies (single-hop)
# ---------------------------------------------------------------------------

def test_ts_single_hop_verified_by_python(fixtures: dict) -> None:
    """Python verifies a TypeScript-signed single-hop delegation JWT."""
    sh = fixtures["single_hop"]
    known_keys = {sh["issuer_did"]: bytes.fromhex(sh["issuer_public_key_hex"])}
    result = verify_auth_chain(
        auth_chain=[sh["token"]],
        expected_subject=sh["subject_did"],
        known_public_keys=known_keys,
    )
    assert result is True, "Python should verify a TS-signed single-hop JWT"


# ---------------------------------------------------------------------------
# Scenario 4 — TypeScript builds 3-hop chain, Python verifies
# ---------------------------------------------------------------------------

def test_ts_three_hop_chain_verified_by_python(fixtures: dict) -> None:
    """Python verifies the full 3-hop chain signed by TypeScript."""
    thc = fixtures["three_hop_chain"]
    # Issuers are parties[0..2]; leaf (parties[3]) is subject only
    known_keys = {
        p["did"]: bytes.fromhex(p["public_key_hex"])
        for p in thc["parties"][:3]
    }
    result = verify_auth_chain(
        auth_chain=thc["chain"],
        expected_subject=thc["expected_subject_did"],
        known_public_keys=known_keys,
    )
    assert result is True, "Python should verify a TS-built 3-hop auth chain"


def test_ts_three_hop_wrong_subject_rejected_by_python(fixtures: dict) -> None:
    """Python rejects the TS chain when expected subject is wrong."""
    thc = fixtures["three_hop_chain"]
    known_keys = {
        p["did"]: bytes.fromhex(p["public_key_hex"])
        for p in thc["parties"][:3]
    }
    result = verify_auth_chain(
        auth_chain=thc["chain"],
        expected_subject=thc["parties"][0]["did"],  # wrong — should be leaf
        known_public_keys=known_keys,
    )
    assert result is False, "Python should reject chain when subject does not match"


# ---------------------------------------------------------------------------
# Scenario 5 — Tampered TS JWT is rejected by Python
# ---------------------------------------------------------------------------

def test_tampered_ts_jwt_rejected_by_python(fixtures: dict) -> None:
    """Python rejects a tampered TypeScript-signed JWT."""
    tt = fixtures["tampered_token"]
    known_keys = {tt["issuer_did"]: bytes.fromhex(tt["issuer_public_key_hex"])}
    result = verify_auth_chain(
        auth_chain=[tt["token"]],
        expected_subject=tt["subject_did"],
        known_public_keys=known_keys,
    )
    assert result is False, "Python should reject a tampered TS-signed JWT"
